// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCipWEdUPKCFYAe0cqjwbK5x3Bd5RU0H0s',
    appId: '1:1026987205210:web:303fa3a6e7f65c6ffeae63',
    messagingSenderId: '1026987205210',
    projectId: 'my-fyp-40911',
    authDomain: 'my-fyp-40911.firebaseapp.com',
    storageBucket: 'my-fyp-40911.appspot.com',
    measurementId: 'G-GGR152T0SS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOkOWlXCsTBL3KdViodl5ZI7nhAgehf9o',
    appId: '1:1026987205210:android:c8ffd6e6d72eef35feae63',
    messagingSenderId: '1026987205210',
    projectId: 'my-fyp-40911',
    storageBucket: 'my-fyp-40911.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr5LXbitC5Bf60v7YCou8i6Pq3aIKSQ_c',
    appId: '1:1026987205210:ios:20b248ff20a94537feae63',
    messagingSenderId: '1026987205210',
    projectId: 'my-fyp-40911',
    storageBucket: 'my-fyp-40911.appspot.com',
    iosClientId: '1026987205210-sc96jai1rej01pbtse9mlbj344m6mh3p.apps.googleusercontent.com',
    iosBundleId: 'com.tml.wsp',
  );
}
